# Generated by Django 5.0 on 2024-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
